/*
 * S7Cord, a Discord client mod
 * Copyright (c) 2026 Vendicated and contributors
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

import "./themedSplash";
import "./ipcCommands";
import "./appBadge";
import "./fixes";
import "./arrpc";
import "./patches/tray";
import "__patches__"; // auto generated by the build script

export * as Components from "./components";

import { openModal } from "@S7Cord/types/utils";
import { onceReady } from "@S7Cord/types/webpack";
import { VoiceActions } from "@S7Cord/types/webpack/common";
import { React } from "@S7Cord/types/webpack/common";

import { SecurityModal } from "./components/SecurityModal";
import SettingsUi from "./components/settings/Settings";
import { VesktopLogger } from "./logger";
import { Settings } from "./settings";
export { Settings };

import type SettingsPlugin from "@S7Cord/types/plugins/_core/settings";
import { VesktopSettingsIcon } from "shared/icons";

VesktopLogger.log("read if cute :3");
VesktopLogger.log(`S7Cord v${VesktopNative.app.getVersion()}`);

const { customEntries, customSections } = S7Cord.Plugins.plugins.Settings as any as typeof SettingsPlugin;

customEntries.push({
    key: "S7Cord_S7Cord_settings",
    title: "S7Cord Settings",
    Component: SettingsUi,
    Icon: VesktopSettingsIcon
});

customSections.push(() => ({
    section: "S7CordSettings",
    label: "S7Cord Settings",
    element: SettingsUi,
    className: "vc-S7Cord-settings"
}));

VesktopNative.voice.onToggleSelfMute(() => VoiceActions.toggleSelfMute());
VesktopNative.voice.onToggleSelfDeaf(() => VoiceActions.toggleSelfDeaf());

// Afficher le SecurityModal uniquement au premier lancement
const SECURITY_MODAL_KEY = "S7Cord_security_modal_seen";
onceReady.then(() => {
    if (!localStorage.getItem(SECURITY_MODAL_KEY)) {
        setTimeout(() => {
            openModal(props => React.createElement(SecurityModal, props));
            localStorage.setItem(SECURITY_MODAL_KEY, "1");
        }, 1500);
    }
});

// TODO: remove this legacy workaround once some time has passed
if (!S7Cord.Api.Styles.S7CordRootNode) {
    const style = document.createElement("style");
    style.id = "vesktop-css-core";
    VesktopNative.app.getRendererCss().then(css => (style.textContent = css));
    document.addEventListener("DOMContentLoaded", () => document.documentElement.append(style), { once: true });
}
