/*
 * S7Cord, a Discord client mod
 * Copyright (c) 2026 Vendicated and contributors
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

import "./themedSplash";
import "./ipcCommands";
import "./appBadge";
import "./fixes";
import "./arrpc";
import "./patches/tray";
import "__patches__"; // auto generated by the build script

export * as Components from "./components";

import { VoiceActions } from "@S7Cord/types/webpack/common";

import SettingsUi from "./components/settings/Settings";
import { VesktopLogger } from "./logger";
import { Settings } from "./settings";
export { Settings };

import type SettingsPlugin from "@S7Cord/types/plugins/_core/settings";
import { VesktopSettingsIcon } from "shared/icons";

VesktopLogger.log("read if cute :3");
VesktopLogger.log(`Equibop v${VesktopNative.app.getVersion()}`);

const { customEntries, customSections } = S7Cord.Plugins.plugins.Settings as any as typeof SettingsPlugin;

customEntries.push({
    key: "S7Cord_equibop_settings",
    title: "Equibop Settings",
    Component: SettingsUi,
    Icon: VesktopSettingsIcon
});

customSections.push(() => ({
    section: "EquibopSettings",
    label: "Equibop Settings",
    element: SettingsUi,
    className: "vc-equibop-settings"
}));

VesktopNative.voice.onToggleSelfMute(() => VoiceActions.toggleSelfMute());
VesktopNative.voice.onToggleSelfDeaf(() => VoiceActions.toggleSelfDeaf());

// TODO: remove this legacy workaround once some time has passed
if (!S7Cord.Api.Styles.S7CordRootNode) {
    const style = document.createElement("style");
    style.id = "vesktop-css-core";
    VesktopNative.app.getRendererCss().then(css => (style.textContent = css));
    document.addEventListener("DOMContentLoaded", () => document.documentElement.append(style), { once: true });
}
